package org.werelate.fte.model
{
	public class TempleCodes
	{
		// the first code is needed for the drop-down menu
		// also, it is returned from getTemple() when there is not a matching code
		public static const codes:Array = [
			{code:"", place:""},
			{code:"ACCRA", place:"Accra, Ghana"},
			{code:"ABA", place:"Aba,Nigeria"},
			{code:"ADELA", place:"Adelaide, Australia"},
			{code:"ALBUQ", place:"Albuquerque, New Mexico"},
			{code:"MTIMP", place:"American Fork, Utah"},
			{code:"ANCHO", place:"Anchorage, Alaska"},
			{code:"SAMOA", place:"Apia, Western Samoa"},
			{code:"ASUNC", place:"Asunción, Paraguay"},
			{code:"ATLAN", place:"Atlanta, Geogria"},
			{code:"BROUG", place:"Baton Rouge, Louisiana"},
			{code:"SWISS", place:"Bern, Switzerland"},
			{code:"BILLI", place:"Billings, Montana"},
			{code:"BIRMI", place:"Birmingham, Alabama"},
			{code:"BISMA", place:"Bismarck, North Dakota"},
			{code:"BOGOT", place:"Bogotá, Colombia"},
			{code:"BOISE", place:"Boise, Idaho"},
			{code:"BOSTO", place:"Boston, Massachusetts"},
			{code:"BOUNT", place:"Bountiful, Utah"},
			{code:"BRISB", place:"Brisbane, Australia"},
			{code:"BAIRE", place:"Buenos Aires, Argentina"},
			{code:"CAMPI", place:"Campinas, Brazil"},
			{code:"CARAC", place:"Caracas, Venezuela"},
			{code:"ALBER", place:"Cardston, Alberta"},
			{code:"CHICA", place:"Chicago, Illinois"},
			{code:"CIUJU", place:"Ciudad Juárez, Chihuahua"},
			{code:"COCHA", place:"Cochabamba, Bolivia"},
			{code:"COLJU", place:"Colonia Juárez, Chihuahua"},
			{code:"COLSC", place:"Columbia, South Carolina"},
			{code:"COLUM", place:"Columbus, Ohio"},
			{code:"CRIVE", place:"Richland, Washington"},
			{code:"COPEN", place:"Copenhagen, Denmark"},
			{code:"DALLA", place:"Dallas, Texas"},
			{code:"DENVE", place:"Denver, Colorado"},
			{code:"DETRO", place:"Detroit, Michigan"},
			{code:"EDMON", place:"Edmonton, Alberta"},
			{code:"FRANK", place:"Frankfurt, Germany"},
			{code:"FRESN", place:"Fresno, California"},
			{code:"FREIB", place:"Freiburg, Germany"},
			{code:"FUKUO", place:"Fukuoka, Japan"},
			{code:"GUADA", place:"Guadalajara, Jalisco"},
			{code:"GUATE", place:"Guatemala City, Guatemala"},
			{code:"GUAYA", place:"Guayaquil, Ecuador"},
			{code:"HALIF", place:"Halifax, Nova Scotia"},
			{code:"NZEAL", place:"Hamilton, New Zealand"},
			{code:"NYORK", place:"Harrison, New York"},
			{code:"HELSI", place:"Helsinki, Finland"},
			{code:"HERMO", place:"Hermosillo, Sonora"},
			{code:"HKONG", place:"Hong Kong, China"},
			{code:"HOUST", place:"Houston, Texas"},
			{code:"IFALL", place:"Idaho Falls, Idaho"},
			{code:"JOHAN", place:"Johannesburg, South Africa"},
			{code:"KONA", place:"Kialua Kona, Hawaii"},
			{code:"KIEV", place:"Kiev, Ukraine"},
			{code:"HAWAI", place:"Laie, Hawaii"},
			{code:"LVEGA", place:"Las Vegas, Nevada"},
			{code:"LIMA", place:"Lima, Peru"},
			{code:"LOGAN", place:"Logan, Utah"},
			{code:"LONDO", place:"London, England"},
			{code:"LANGE", place:"Los Angeles, California"},
			{code:"LOUIS", place:"Louisville, Kentucky"},
			{code:"LUBBO", place:"Lubbock, Texas"},
			{code:"MADRI", place:"Madrid, Spain"},
			{code:"MANIL", place:"Manila, Philippines"},
			{code:"MANTI", place:"Manti, Utah"},
			{code:"MEDFO", place:"Medford, Oregon"},
			{code:"MELBO", place:"Melbourne, Australia"},
			{code:"MEMPH", place:"Memphis, Tennessee"},
			{code:"MERID", place:"Mérida, Yucatán"},
			{code:"ARIZO", place:"Mesa, Arizona"},
			{code:"MEXIC", place:"Mexico City, D.F."},
			{code:"MONTE", place:"Monterrey, Nuevo Leon"},
			{code:"MNTVD", place:"Montevideo, Uruguay"},
			{code:"MONTI", place:"Monticello, Utah"},
			{code:"MONTR", place:"Montréal, Québec"},
			{code:"NASHV", place:"Nashville, Tennessee"},
			{code:"NAUVO", place:"Nauvoo, Illinois (first)"},
			{code:"NAUV2", place:"Nauvoo, Illinois (second)"},
			{code:"NBEAC", place:"Newport Beach, California"},
			{code:"MANHA", place:"New York, New York"},
			{code:"NUKUA", place:"Nuku'alofa, Tonga"},
			{code:"OAKLA", place:"Oakland, California"},
			{code:"OAXAC", place:"Oaxaca, Oaxaca"},
			{code:"OGDEN", place:"Ogden, Utah"},
			{code:"OKLAH", place:"Oklahoma City, Oklahoma"},
			{code:"WINTE", place:"Omaha, Nebraska"},
			{code:"ORLAN", place:"Orlando, Florida"},
			{code:"PALMY", place:"Palmayra, New York"},
			{code:"PAPEE", place:"Papeete, Tahiti"},
			{code:"PERTH", place:"Perth, Australia"},
			{code:"PORTL", place:"Portland, Oregon"},
			{code:"PALEG", place:"Porto Alegre, Brazil"},
			{code:"PREST", place:"Preston, England"},
			{code:"PROVO", place:"Provo, Utah"},
			{code:"RALEI", place:"Raleigh, North Carolina"},
			{code:"RECIF", place:"Recife, Brazil"},
			{code:"REDLA", place:"Redlands, California"},
			{code:"REGIN", place:"Regina, Saskatchewan"},
			{code:"RENO", place:"Reno, Nevada"},
			{code:"SGEOR", place:"St. George, Utah"},
			{code:"SLOUI", place:"St. Louis, Missouri"},
			{code:"SPMIN", place:"St. Paul, Minnesota"},
			{code:"SLAKE", place:"Salt Lake City, Utah"},
			{code:"SDIEG", place:"San Diego, California"},
			{code:"SACRA", place:"Sacramento, California"},
			{code:"SANTO", place:"San Antonio, Texas"},
			{code:"SJOSE", place:"San José, Costa Rica"},
			{code:"SANTI", place:"Santiago, Chile"},
			{code:"SDOMI", place:"Santo Domingo, Dom. Rep."},
			{code:"SPAUL", place:"São Paulo, Brazil"},
			{code:"SEATT", place:"Seattle, Washington"},
			{code:"SEOUL", place:"Seoul, Korea"},
			{code:"SNOWF", place:"Snowflake, Arizona"},
			{code:"JRIVE", place:"South Jordan, Utah"},
			{code:"SPOKA", place:"Spokane, Washington"},
			{code:"STOCK", place:"Stockholm, Sweden"},
			{code:"SUVA", place:"Suva, Fiji"},
			{code:"SYDNE", place:"Sydney, Australia"},
			{code:"TAIPE", place:"Taipei, Taiwan"},
			{code:"TAMPI", place:"Tampico, Tamaulipas"},
			{code:"HAGUE", place:"The Hague, Netherlands"},
			{code:"TOKYO", place:"Tokyo, Japan"},
			{code:"TORON", place:"Toronto, Ontario"},
			{code:"TGUTI", place:"Tuxtla Gutiérrez, Chiapas"},
			{code:"VERAC", place:"Vera Cruz, Vera Cruz"},
			{code:"VERNA", place:"Vernal, Utah"},
			{code:"VILLA", place:"Villahermosa, Tabasco"},
			{code:"WASHI", place:"Washington, D.C."}
		];

		public static function getTemple(code:String):Object {
			if (code != null) {
				for (var i:int = 0; i < TempleCodes.codes.length; i++) {
					if (code == TempleCodes.codes[i].code) {
						return TempleCodes.codes[i];
					}
				}
			}
			return TempleCodes.codes[0];
		}	
	}
}